def patterned_dog(color):
    dog_colors_with_patterns = { 'Black Brindle',
                                 'Black Brindle/Black',
                                 'Black Brindle/Brown',
                                 'Black Brindle/Brown Brindle',
                                 'Black Brindle/White',
                                 'Black/Black Brindle',
                                 'Black/Blue Tick',
                                 'Black/Brown Brindle',
                                 'Black/Tricolor',
                                 'Black/Yellow Brindle',
                                 'Blue Merle/Tricolor',
                                 'Blue Tick',
                                 'Blue Tick/Black',
                                 'Blue Tick/Brown',
                                 'Blue Tick/Brown Brindle',
                                 'Blue Tick/Red',
                                 'Blue Tick/Red Tick',
                                 'Blue Tick/Tan',
                                 'Blue Tick/White',
                                 'Blue/Brown Brindle',
                                 'Blue/Yellow Brindle',
                                 'Brown Brindle',
                                 'Brown Brindle/Black',
                                 'Brown Brindle/Blue',
                                 'Brown Brindle/Blue Cream',
                                 'Brown Brindle/Blue Tick',
                                 'Brown Brindle/Brown Brindle',
                                 'Brown Brindle/Brown Merle',
                                 'Brown Brindle/Red Tick',
                                 'Brown Brindle/Tan',
                                 'Brown Brindle/White',
                                 'Brown/Black Brindle',
                                 'Brown/Red Tick',
                                 'Brown/Tricolor',
                                  'Chocolate/Brown Brindle',
                                 'Chocolate/Red Tick',
                                 'Chocolate/Tricolor',
                                 'Cream/Red Tick',
                                 'Fawn/Brown Brindle',
                                 'Fawn/Tricolor',
                                 'Liver Tick',
                                 'Liver Tick/White',
                                 'Red Tick',
                                 'Red Tick/Black',
                                 'Red Tick/Blue Tick',
                                 'Red Tick/Brown',
                                 'Red Tick/Brown Merle',
                                 'Red Tick/Red',
                                 'Red Tick/Tan',
                                 'Red Tick/White',
                                 'Red/Red Tick',
                                 'Red/Tricolor',
                                 'Tan/Brown Brindle',
                                 'Tan/Tricolor',
                                 'Tan/Yellow Brindle',
                                 'Tricolor',
                                 'Tricolor/Black',
                                 'Tricolor/Blue',
                                 'Tricolor/Blue Merle',
                                 'Tricolor/Brown',
                                 'Tricolor/Brown Merle',
                                 'Tricolor/Chocolate',
                                 'Tricolor/Silver',
                                 'Tricolor/Tan',
                                 'Tricolor/White',
                                 'White/Black Brindle',
                                 'White/Blue Tick',
                                  'White/Brown Brindle',
                                 'White/Red Tick',
                                 'White/Tricolor',
                                 'White/Yellow Brindle',
                                 'Yellow Brindle',
                                 'Yellow Brindle/Blue',
                                 'Yellow Brindle/Tan',
                                 'Yellow Brindle/White' }

    if color in dog_colors_with_patterns:
        return 1
    else:
        return 0

def patterned_cat(color):
    cat_colors_with_patterns = {'Agouti',
                                'Agouti/Brown Tabby',
                                'Brown Tiger',
                                'Black Tiger/White',
                                'Orange Tiger',
                                'Tricolor',
                                'Calico/Tricolor',
                                'Tricolor/Calico',
                                'Black Smoke/White',
                                'Black Smoke',
                                'Blue Smoke',
                                'Black/Black Smoke',
                                'Black Smoke/Brown Tabby',
                                'Chocolate/Black Smoke',
                                'White/Black Smoke',
                                'Tortie/Black Smoke',
                                'Cream Tabby',
                                'Blue Tabby',
                                'Orange Tabby/White',
                                'Brown Tabby',
                                'Orange Tabby',
                                'Cream Tabby/White',
                                'Blue Tabby/White',
                                'Brown Tabby/White',
                                'Black Tabby/White',
                                'White/Cream Tabby',
                                'White/Blue Tabby',
                                'White/Brown Tabby',
                                'White/Orange Tabby',
                                'Gray Tabby',
                                'Blue Tabby/Orange',
                                'Black Tabby',
                                'Calico/Brown Tabby',
                                'Silver Tabby',
                                'White/Black Tabby',
                                'Black/Silver Tabby',
                                'Blue Tabby/Blue Cream',
                                'Brown Tabby/Black',
                                'Gray Tabby/White',
                                'Black Tabby/Orange',
                                'Silver Tabby/White',
                                'Black Smoke/Brown Tabby',
                                'Blue Tabby/Tan',
                                'Black/Black Tabby',
                                'Brown Tabby/Gray',
                                'Brown/Black Tabby',
                                'Lynx Point/Brown Tabby',
                                'Orange Tabby/Black',
                                'Brown Tabby/Brown',
                                'White/Gray Tabby',
                                'Calico/Orange Tabby',
                                'Agouti/Brown Tabby',
                                'Brown Tabby/Tortie',
                                'Lynx Point/Gray Tabby',
                                'Blue Tabby/Cream',
                                'Silver Tabby/Black',
                                'Orange Tabby/Orange',
                                'Brown Tabby/Orange',
                                'Blue Cream/Blue Tabby',
                                'Calico/Blue Tabby',
                                'Brown Tabby/Gray Tabby',
                                'Lynx Point/White',
                                'Lynx Point',
                                'Tortie Point/Lynx Point',
                                'White/Lynx Point',
                                'Lynx Point/Brown Tabby',
                                'Silver Lynx Point',
                                'Lynx Point/Gray Tabby',
                                'Flame Point',
                                'Blue Point',
                                'Seal Point',
                                'Lynx Point/White',
                                'Lilac Point',
                                'Tortie Point',
                                'Lynx Point',
                                'Calico Point',
                                'Tortie Point/Lynx Point',
                                'White/Chocolate Point',
                                'Calico Point/White',
                                'Seal Point/White',
                                'Chocolate Point/White',
                                'White/Lynx Point',
                                'Blue Point/White',
                                'Chocolate Point',
                                'Seal Point/Brown',
                                'Lynx Point/Brown Tabby',
                                'Silver Lynx Point',
                                'Tortie Point/White',
                                'White/Flame Point',
                                'Cream/Seal Point',
                                'Lynx Point/Gray Tabby',
                                'Calico',
                                'Tortie/Calico',
                                'Calico Point',
                                'Calico/White',
                                'Calico Point/White',
                                'Calico/Brown Tabby',
                                'Calico/Black',
                                'Calico/Tricolor',
                                'Calico/Brown',
                                'Torbie/Calico',
                                'Calico/Orange Tabby',
                                'White/Calico',
                                'Calico/Blue Cream',
                                'Calico/Blue Tabby',
                                'Tricolor/Calico',
                                'Tortie',
                                'Tortie/Calico',
                                'Tortie Point',
                                'Tortie/White',
                                'Tortie Point/Lynx Point',
                                'Tortie/Blue Cream',
                                'Blue/Tortie',
                                'Tortie/Orange',
                                'Tortie/Brown',
                                'Tortie/Black',
                                'Tortie Point/White',
                                'Brown Tabby/Tortie',
                                'Tortie/Black Smoke',
                                'Blue Cream/Tortie',
                                'Torbie',
                                'Torbie/White',
                                'Torbie/Brown',
                                'Torbie/Blue Cream',
                                'Torbie/Calico'}

    if color in cat_colors_with_patterns:
        return 1
    else:
        return 0



def multi_dog(color):
    solid_dog_colors = { 'Tan',
                         'White',
                         'Silver',
                         'Brown',
                         'Black',
                         'Yellow',
                         'Buff',
                         'Red',
                         'Brown Brindle',
                         'Gray',
                         'Blue Merle',
                         'Sable',
                         'Cream',
                         'Chocolate',
                         'Fawn',
                         'Blue',
                         'Apricot',
                         'Yellow Brindle',
                         'Gold',
                         'Blue Tick',
                         'Red Merle',
                         'Black Brindle',
                         'Brown Merle',
                         'Red Tick',
                         'Liver Tick',
                         'Blue Tiger',
                         'Orange',
                         'Brown Tiger',
                         'Black Smoke' }

    if color in solid_dog_colors:
        return 0
    else:
        return 1

def multi_cat(color):
    solid_cat_colors = { 'Apricot',
                         'Black',
                         'Black Brindle',
                         'Black Smoke',
                         'Blue',
                         'Blue Merle',
                         'Blue Tick',
                         'Blue Tiger',
                         'Brown',
                         'Brown Brindle',
                         'Brown Merle',
                         'Brown Tiger',
                         'Buff',
                         'Chocolate',
                         'Cream',
                         'Fawn',
                         'Gold',
                         'Gray',
                         'Liver Tick',
                         'Orange',
                         'Red',
                         'Red Merle',
                         'Red Tick',
                         'Sable',
                         'Silver',
                         'Tan',
                         'Tricolor',
                         'White',
                         'Yellow',
                         'Yellow Brindle' }

    if color in solid_cat_colors:
        return 0
    else:
        return 1
